name: vault
summary: Vault is a tool for securely accessing secrets.
description: |
  A modern system requires access to a multitude of secrets: database
  credentials, API keys for external services, credentials for service-oriented
  architecture communication, etc. Understanding who is accessing what secrets
  is already very difficult and platform-specific. Adding on key rolling,
  secure storage, and detailed audit logs is almost impossible without a custom
  solution. This is where Vault steps in.
base: core18

grade: stable
confinement: strict
adopt-info: vault

apps:
  vault:
    command: bin/vault
    plugs:
      - network
      - network-bind
      - home

parts:
  vault:
    source: https://github.com/hashicorp/vault.git
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_released_tag="$(snap info vault | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git checkout "${last_committed_tag}"
        # XXX The snapcraft go plugin builds a link to the src dir, not to the
        # build dir. That might be a bug, but let's better checkout both to be
        # safe that we are not building the wrong thing. --elopio - 20171108
        cd ../src
        git checkout "${last_committed_tag}"
      fi
      git apply $SNAPCRAFT_STAGE/etcd_export_tls_no_verify.patch
      git apply $SNAPCRAFT_STAGE/ubuntu-fan.patch
      snapcraftctl set-version `echo ${last_committed_tag} | sed "s/v//g"`
    plugin: go
    go-importpath: github.com/hashicorp/vault
    go-buildtags:
      - vault
    go-channel: 1.10/stable
    build-packages:
      - git
      - g++
      - libsasl2-dev
    after:
      - patches
  patches:
    source: ./snap/local/patches
    plugin: dump
    prime:
      - -*
