name: vault
summary: Vault is a tool for securely accessing secrets.
description: |
  A modern system requires access to a multitude of secrets: database
  credentials, API keys for external services, credentials for service-oriented
  architecture communication, etc. Understanding who is accessing what secrets
  is already very difficult and platform-specific. Adding on key rolling,
  secure storage, and detailed audit logs is almost impossible without a custom
  solution. This is where Vault steps in.
base: core18

grade: stable
confinement: strict
adopt-info: vault

apps:
  vault:
    command: bin/vault
    plugs:
      - network
      - network-bind
      - home

parts:
  vault:
    source: https://github.com/hashicorp/vault.git
    source-branch: release/1.6.x
    override-pull: |
      set -x
      snapcraftctl pull
      release_tag="$(git tag -l --sort=version:refname "v1.6.*" | tail -1)"
      # If the latest tag from the upstream project has not been released to
      git checkout "${release_tag}"
      git apply $SNAPCRAFT_STAGE/etcd_export_tls_no_verify.patch
      git apply $SNAPCRAFT_STAGE/ubuntu-fan.patch
      snapcraftctl set-version `echo ${release_tag} | sed "s/v//g"`
    plugin: go
    go-importpath: github.com/hashicorp/vault
    go-buildtags:
      - vault
    go-channel: 1.15/stable
    build-packages:
      - git
      - g++
      - libsasl2-dev
    after:
      - patches
  patches:
    source: ./snap/local/patches
    plugin: dump
    prime:
      - -*
