name: Protected branch workflow

on:
  push:
    branches:
      - master
      - 'stable/**'
  pull_request:
    branches:
      - master
      - 'stable/**'
  schedule:
    - cron: '0 6 * * 0'

concurrency:
    group: ${{ github.ref == 'refs/heads/master' && format('ignore-master-{0}', github.run_id) || format('{0}-{1}', github.workflow, github.ref_name) }}
    cancel-in-progress: true

jobs:
  build:
    name: Build snap
    uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@v22.0.0

  release:
    name: Release snap
    needs:
      - build
    uses: canonical/data-platform-workflows/.github/workflows/release_snap.yaml@v22.0.0
    with:
      channel: 1.17/edge
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    secrets:
      snap-store-token: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
    permissions:
      contents: write  # Needed to create GitHub release

  test-service:
    name: Test snap service
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download snap artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{needs.build.outputs.artifact-prefix}}-amd64

      - name: Install snap
        run: |
          SNAP_NAME=$(ls *.snap)
          echo "Installing snap $SNAP_NAME"
          sudo snap install --dangerous $SNAP_NAME

      - name: Start the vault snap service
        run: |
          sudo snap start vault
          sleep 30

      - name: Test snap service
        run: |
          sudo apt-get update
          sudo apt-get install -y net-tools
          # Check if a service is listening on port 8200
          if netstat -tuln | grep ':8200'; then
            echo "Service is listening on port 8200"
          else
            echo "Service is NOT listening on port 8200"
            exit 1
          fi
