name: Protected branch workflow

on:
  push:
    branches:
      - master
      - 'stable/**'
  pull_request:
    branches:
      - master
      - 'stable/**'
  schedule:
    - cron: '0 6 * * 0'

jobs:
  build:
    name: Build snap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build snap locally
        uses: snapcore/action-build@v1
        id: build
      
      - name: Get snapcraft track
        if: ${{ github.ref_protected }}
        id: track
        run: |
          if [ "${{ github.ref_name }}" == "master" ]; then
            echo "::set-output name=track::latest"
          elif [[ "${{ github.ref_name }}" =~ ^stable\/(.+) ]]; then
            TRACK_NAME=${BASH_REMATCH[1]}
            echo "::set-output name=track::$TRACK_NAME"
          else
            echo "Branch name does not match expected patterns. Exiting."
            exit 1
          fi
      
      - name: publish snap
        if: ${{ github.ref_protected }}
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: ${{ steps.track.outputs.track }}/edge
