name: Protected branch workflow

on:
  push:
    branches:
      - master
      - */stable
  pull_request:
    branches:
      - master
      - */stable

jobs:
  build:
    name: Build snap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Build snap locally
      #   uses: snapcore/action-build@v1
      #   id: build
      
      - name: Get snapcraft track
      # if: ${{ github.ref_name == 'master' }}
        id: track
        run: |
          if [ "${{ github.ref_name }}" == "master" ]; then
            echo "::set-output name=track::master"
          else
            echo "::set-output name=track::$(yq -r .version snap/snapcraft.yaml)"
          fi
          echo "Track: ${{ steps.track.outputs.track }}"
          
      # - name: publish snap
      #   # if: ${{ github.ref_name == 'master' }}
      #   uses: snapcore/action-publish@v1
      #   env:
      #     SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
      #   with:
      #     snap: ${{ steps.build.outputs.snap }}
      #     release: ${{ steps.track.outputs.track }}/edge
